/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SystemMonitor': CronHandler<{ topic: 'incident.detected'; data: never }>
    'MetricsAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'IncidentsAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AutoExecuteFix': EventHandler<never, { topic: 'incident.resolved'; data: never }>
    'ExecuteFix': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'incident.resolved'; data: never }>
    'DashboardUI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CompletionLogger': EventHandler<never, never>
    'ChaosService': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'incident.detected'; data: never }>
    'AnalysisAgent': EventHandler<never, { topic: 'fix.proposed'; data: never }>
  }
    
}